[package]
name = "keyforge-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
kle-serial = "0.3.3"
clap = { version = "4.4", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
